[front]1013 - Tournseol video's url now works for copy/paste in comparisons
tournesol-app/tournesol pull request #1033
Opened 2022-07-06 15:11 UTC by Sbyspaceopera

I kept the original way, just improved the RegExp in `./frontend/src/utils/video.ts`

You can visualize the new RegExp workflow [here](https://regexper.com/#%2F%28%3F%3Ahttps%3F%3A%5C%2F%5C%2F%29%3F%28%3F%3Awww%5C.%29%3F%28%3F%3Ayoutube%5C.com%5C%2Fwatch%5C%3Fv%3D%7Cyoutu.be%5C%2F%7Ctournesol%5C.app%5C%2Fentities%5C%2Fyt%3A%29%28%5BA-Za-z0-9-_%5D%2B%29%2F)  on [RegExper.com](url)

2022-07-06 15:28 UTC, GresilleSiffle commented on frontend/src/utils/video.ts
> +    /(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/watch\?v=|youtu.be\/|tournesol\.app\/entities\/yt:)([A-Za-z0-9-_]+)/
I found an old bug in the original regex.

Look the middle path:
 
![capture](https://user-images.githubusercontent.com/39056254/177587285-e7ec79fb-5ec0-4672-bfec-e97e76aee7be.png)

It shouldn't accept any character, only the dot:

![capture2](https://user-images.githubusercontent.com/39056254/177587394-785949a3-2a0c-4453-96a2-7b647cced1e4.png)

Accepting this suggestion will fix the problem.

```suggestion
    /(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/watch\?v=|youtu\.be\/|tournesol\.app\/entities\/yt:)([A-Za-z0-9-_]+)/
```

2022-07-06 15:42 UTC, GresilleSiffle requested changes
This looks good, thanks for the work :+1: 

I found few limitations:
- it won't work on staging, because the staging hostname is `staging.tournesol.app`
- it won't work in local, because the string `localhost:3000` != `tournesol.app`

We have several options:
1. use the `location.host` variable instead of the string `tournesol.app`
2. hardcode `staging` and `localhost:{port}` in the regex
3. something else?

The side effects of the option 1:
- copy/pasting URLs between local and staging and production will work.
- we can change of domain name, the copy/paste will still work

2022-07-07 16:07 UTC, Sbyspaceopera commented
@GresilleSiffle I think that the first solution is quite clean. I'll work on it this night or tomorow.

Note that `location.host` can't be used as it is in a regex litteral : 

- This can be done with the `RegExp` Object constructor. 
- Some characters in the value returned by `location.host` needs to be escaped automatically to not conflict with the regex, just as we seen it with `youtu.be`.

2022-07-11 12:24 UTC, GresilleSiffle commented
It looks good, we can even use this:

```javascript
  let host = process.env.PUBLIC_URL;
  if (!host) {
    host = location.host;
  }

  const escapedCurrentHost = host.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

  const matchUrl = idOrUrl.match(
    new RegExp(
      '(?:https?:\\/\\/)?(?:www\\.)?(?:youtube\\.com\\/watch\\?v=|youtu\\.be\\/|' +
        escapedCurrentHost +
        '\\/entities\\/yt:)([A-Za-z0-9-_]+)'
    )
  );
```

Here we use the public URL configured by the environment variables. This variable may not be defined in development environments (like the `dev-env`) so there is a fallback on the browser API `location`.

2022-07-14 12:56 UTC, Sbyspaceopera commented
I just commit the @GresilleSiffle version.

I also reduce this line :

`const escapedCurrentHost = host.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');`

To this :

`const escapedCurrentHost = host.replace(/[.\\]/g, '\\$&');`

As "jst" mentionned on the Discord, there was a lot of unnecessary escaping in this regex regarding our urls.

Is it ok like this for you?

2022-07-14 13:39 UTC, GresilleSiffle commented on frontend/src/utils/video.ts
> +    /(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/watch\?v=|youtu.be\/|tournesol\.app\/entities\/yt:)([A-Za-z0-9-_]+)/
Fixed by 7b11bff05fb208e35503b6f9c8b8b90425ec2926.

2022-07-14 14:02 UTC, GresilleSiffle approved these changes

2022-07-14 14:02 UTC, merged