Back: add duration of video
tournesol-app/tournesol pull request #318
Opened 2021-11-25 10:19 UTC by sandre35

2021-11-26 20:08 UTC, lfaucon commented on backend/tournesol/serializers.py
> +        return 0
@sandre35 @GresilleSiffle @amatissart 

There is some code duplication between `VideoSerializer` and `VideoSerializerWithCriteria`


Could this be refactored into 

```
class VideoSerializerWithCriteria(VideoSerializer):
    criteria_scores = VideoCriteriaScoreSerializer(many=True)
    
    class Meta(VideoSerializer.Meta):
        fields = VideoSerializer.Meta.fields + ['criteria_scores'] 
```

2021-11-26 20:43 UTC, lfaucon approved these changes
Looks good to me. Approving with suggestion & question

2021-11-26 20:43 UTC, lfaucon commented on backend/requirements.txt
> +isodate
Can you document it in `python_dependency.md`? Explain where we use it and why.

2021-11-29 09:54 UTC, amatissart requested changes

2021-11-29 09:54 UTC, amatissart commented on backend/requirements.txt
> +isodate
The version used should be specified, to avoid potential breakage when a new version is available:
```suggestion
isodate==0.6.0
```

2021-11-29 09:54 UTC, amatissart commented on backend/tournesol/serializers.py
> +        return 0
A type hint is necessary, so as to the correct type appears in the OpenAPI schema.  
Also, I would recommend to return `null` when the duration is not defined, to make sure the frontend handles this case explicitly.
```suggestion
    # Convert duration to seconds to facilitate use of Humanize package
    def get_duration(self, obj) -> Optional[int]:
        if obj.duration:
            return int(obj.duration.total_seconds())
        return None
```

2021-11-29 09:56 UTC, amatissart commented
@sandre35 This branch needs to be rebased on main, as there are minor conflicts after changes introduced by #257.

2021-12-02 10:17 UTC, amatissart approved these changes

2021-12-03 14:19 UTC, merged