display video duration on Front
tournesol-app/tournesol pull request #321
Opened 2021-11-26 14:32 UTC by sandre35

Linked issue : https://github.com/tournesol-app/tournesol/issues/282
This PR tackles steps 3 and 4.

2021-11-26 15:15 UTC, sandre35 commented
![Screenshot from 2021-11-26 16-12-58](https://user-images.githubusercontent.com/65041823/143601299-35407a7d-0f2a-4ad7-9493-ac67a69b59d1.png)
the first video has the duration registered in the db, contrary to the second one

2021-11-26 20:48 UTC, lfaucon commented on frontend/yarn.lock
> +  resolved "https://registry.npmjs.org/@apidevtools/json-schema-ref-parser/-/json-schema-ref-parser-9.0.9.tgz"
You probably should not have these changes. Did you run `npm install` instead of `yarn install` ?

2021-11-26 20:54 UTC, lfaucon requested changes
Could we display the duration more similarly as on Youtube? Maybe there is an option with ReactPlayer ? Otherwise, we may write our own VideoPlayer component to be used in VideoCard, VideoSelector & VideoThumb.

![Screenshot 2021-11-26 at 21 49 09](https://user-images.githubusercontent.com/8818081/143637018-c7296b93-ab94-47a2-9ad6-f0049404d5b2.png)

2021-12-03 14:10 UTC, sandre35 commented
@lfaucon there is no parameter that enables us to print the duration of the video on preview with ReactPlayer options.

2021-12-10 10:28 UTC, amatissart commented on frontend/scripts/openapi.yaml
> +          description: Duration of the video
This file does not seem to be up to date with the API. This field `duration` is supposed to be "nullable".

2021-12-10 10:28 UTC, amatissart commented on frontend/src/features/videos/VideoCard.tsx
> +          )}
After some experiments, I end up with a potential solution to display the duration in the bottom-right corner of the player, using the [`wrapper` prop](https://github.com/cookpete/react-player#props).

Here is what the wrapper could look like:
```tsx
const PlayerWrapper = ({
  duration,
  children,
}: {
  duration?: string;
  children: React.ReactNode;
}) => {
  const [isDurationVisible, setIsDurationVisible] = useState(true);
  return (
    <Box
      position="relative"
      height="100%"
      onClick={() => setIsDurationVisible(false)}
    >
      {isDurationVisible && duration && (
        <Box
          position="absolute"
          bottom={0}
          right={0}
          bgcolor="rgba(0,0,0,0.5)"
          color="#fff"
          px={1}
          fontSize="0.8em"
          fontWeight="bold"
        >
          {duration}
        </Box>
      )}
      {children}
    </Box>
  );
};
```

2021-12-12 20:25 UTC, lfaucon approved these changes
I changed `convertDurationToClockDuration` to not display hours when the duration is < 1 hour. Thanks for this, it looks great :)

2021-12-13 09:44 UTC, amatissart commented on frontend/src/features/videos/VideoCard.tsx
> +          fontWeight="bold"
A small bug: the duration block will disappear if you click on it. We would probably prefer that pointer events pass through this block.

```suggestion
          fontWeight="bold"
          style={{ pointerEvents: 'none' }}
```

2021-12-13 09:44 UTC, amatissart commented on frontend/src/features/videos/VideoCard.tsx
> +    marginRight: '12px',
No longer relevant in this PR.

2021-12-16 09:56 UTC, amatissart approved these changes

2021-12-17 13:58 UTC, merged