[front] feat: Add language selector in footer
tournesol-app/tournesol pull request #454
Opened 2022-01-13 16:27 UTC by amatissart

To be merged after #450 

![image](https://user-images.githubusercontent.com/4726554/149368974-81b49ff7-877a-4f7d-b098-8ae9f824c3f3.png)

2022-01-13 16:29 UTC, amatissart commented on frontend/package.json
> +    "typescript": "~4.5.4",
Upgrade required in order to type correctly `Int.DisplayNames` (used to get language names)

2022-01-13 16:31 UTC, amatissart commented on frontend/src/features/settings/account/ExportAllDataForm.tsx
> +      const zipFileBlob = await response.blob();
Fixes a Typescript error (not sure why it was not triggered by the previous version).

2022-01-14 17:02 UTC, lfaucon requested changes

2022-01-14 17:02 UTC, lfaucon commented on frontend/src/components/LanguageSelector.tsx
> +          >
Could this show which language is selected?

2022-01-14 19:31 UTC, lfaucon approved these changes
💯

2022-01-14 19:39 UTC, merged